"""
Data contracts for Itinerary, Daily Plans, and Activities.
"""

import uuid
from typing import List, Optional
from pydantic import BaseModel, Field


class Activity(BaseModel):
    """Individual scheduled activity for a morning, afternoon, or evening slot."""

    time_slot: str = Field(
        ...,
        description="Time of day: 'Morning', 'Afternoon', or 'Evening'",
    )
    title: str = Field(
        ...,
        description="Name of the attraction, venue, or activity",
    )
    description: str = Field(
        ...,
        description="Actionable travel advice or highlight for this activity",
    )
    cost: float = Field(
        default=0.0,
        ge=0.0,
        description="Estimated cost in the trip currency (0.0 if free)",
    )
    is_indoor: bool = Field(
        default=False,
        description="True if this is an indoor activity (crucial for rain adaptation)",
    )
    location: str = Field(
        ...,
        description="Neighborhood, district, or landmark area",
    )


class DayPlan(BaseModel):
    """Daily travel plan containing scheduled activities."""

    day_number: int = Field(..., ge=1, description="Sequential day number (1-indexed)")
    theme: str = Field(..., description="Focus or theme of the day")
    weather_summary: Optional[str] = Field(
        default=None,
        description="Expected weather condition for this day",
    )
    activities: List[Activity] = Field(
        ...,
        min_length=1,
        description="Scheduled activities for this day",
    )


class Itinerary(BaseModel):
    """Final structured itinerary generated by the agent and verified by guardrails."""

    trip_id: str = Field(
        default_factory=lambda: f"trip_{uuid.uuid4().hex[:6]}",
        description="Unique identifier for this generated itinerary",
    )
    destination: str = Field(..., description="Target destination city")
    duration_days: int = Field(..., ge=1, description="Total days planned")
    currency: str = Field(default="USD", description="Currency for all activity costs")
    days: List[DayPlan] = Field(..., min_length=1, description="Day-by-day plan")
    total_cost: float = Field(
        default=0.0,
        description="Deterministically calculated total cost of all activities",
    )
    budget: float = Field(
        default=0.0,
        description="Target user budget limit",
    )
    is_within_budget: bool = Field(
        default=True,
        description="Whether total cost complies with user budget",
    )
    weather_overview: str = Field(
        default="",
        description="Overall weather outlook across the trip",
    )
